# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

#language: c
#language: java
language: r

bioc_required: true

# System dependencies for HTTP calling
r_packages:
#  - RUnit

r_binary_packages:
  - matrixStats
  - ggplot2
  - foreach
  - RUnit
  - plyr
  - xlsx

r_github_packages:

bioc_packages
  - exomeCopy
  - cn.mops
  - BiocGenerics
  - Rsamtools

before_install:
  - sudo apt-get install -y libjvm
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh aptget_install r-cran-rjava
  - sudo R CMD javareconf
#  - ./travis-tool.sh bioc_install exomeCopy cn.mops BiocGenerics Rsamtools
#  - ./travis-tool.sh install_aptget matrixStats ggplot2 foreach RUnit plyr xlsx
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

sudo: required

env:
  - global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - LD_LIBRARY_PATH=/usr/lib/jvm/java-7-oracle/lib/amd64:/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server
